backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Сторінки"
    files:
      - file: "src/pages/index.md"
        label: "Головна"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Hero Image, name: heroImage, widget: image }
          - { label: Hero Title, name: heroTitle, widget: string }
          - { label: Hero Subtitle, name: heroSubtitle, widget: string }
          - { label: Body, name: body, widget: markdown }
      - file: "src/pages/donate.md"
        label: "Підтримка"
        name: "donate"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "donate-page",
            }
          - { label: Hero Image, name: heroImage, widget: image }
          - { label: Hero Title, name: heroTitle, widget: string }
          - { label: Hero Subtitle, name: heroSubtitle, widget: string }
          - { label: Body, name: body, widget: markdown }
  - name: "product"
    label: "Продукти"
    folder: "src/pages/product"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "product-item",
        }
      - { label: Is Visible, name: isVisible, widget: boolean }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Hero Image, name: heroImage, widget: image }
      - { label: Hero Title, name: heroTitle, widget: string }
      - { label: Hero Subtitle, name: heroSubtitle, widget: string }
      - { label: Body, name: body, widget: markdown }
  - name: "article"
    label: "База знань"
    folder: "src/pages/article"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "article-item",
        }
      - { label: Is Visible, name: isVisible, widget: boolean }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Hero Image, name: heroImage, widget: image }
      - { label: Hero Title, name: heroTitle, widget: string }
      - { label: Hero Subtitle, name: heroSubtitle, widget: string }
      - { label: Body, name: body, widget: markdown }
      - { label: Wiki Categories, name: wikiCategories, widget: list }
  - name: "partner"
    label: "Партнери"
    folder: "src/pages/partner"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "partner-item",
        }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Partner Image, name: partnerImage, widget: image }
      - { label: Title, name: title, widget: string }
      - { label: Partner Link, name: partnerLink, widget: string }
